#!/bin/sh

### BEGIN INIT INFO
# Provides:          node-red
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Node-RED at boot time
# Description:       Start Node-RED service.
### END INIT INFO

DAEMON=/usr/local/bin/node-red
DAEMON_OPTS="--max-old-space-size=64"
NAME=node-red
DESC="Node-RED service"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
USER=recamera 

start() {
    echo "Starting $DESC: $NAME"

    if id "$USER" &>/dev/null; then
        DAEMON_USER=$USER
    else
        DAEMON_USER=root
        exit 1
    fi

    if [ -f $PIDFILE ]; then
        echo "$NAME is already running."
    else
        start-stop-daemon -S -q -m -b -p $PIDFILE \
                --chuid $DAEMON_USER --exec $DAEMON -- $DAEMON_OPTS
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    fi
}

stop() {
    echo "Stopping $DESC: $NAME"
    if [ -f $PIDFILE ]; then
        start-stop-daemon -K -q -p $PIDFILE
        rm -f $PIDFILE
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    else
        echo "$NAME is not running."
    fi
}

restart() {
    stop
    start
}

status() {
    if [ -f $PIDFILE ]; then
        echo "$NAME is running."
    else
        echo "$NAME is not running."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0