#!/bin/sh
set -e

ln -sf  /usr/lib/node-red/packages/node_modules/node-red/bin/node-red-pi /usr/local/bin/node-red

if [ -f /etc/init.d/S92node-red ]; then
    /etc/init.d/S92node-red start   
fi


exit 0